#ifdef NL_OS_WINDOWS

#define USE_JPEG

#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <climits>
#include <clocale>
#include <cmath>
#include <complex>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cwchar>
#include <cwctype>

#include <algorithm>
#include <bitset>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <hash_map>
#include <hash_set>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <new>
#include <numeric>
#include <ostream>
#include <queue>
#include <rope>
#include <set>
#include <slist>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <streambuf>
#include <string>
#include <strstream>
#include <typeinfo>
#include <utility>
#include <valarray>
#include <vector>

#include <nel/misc/types_nl.h>
#include <nel/misc/debug.h>

#include <nel/misc/aabbox.h>
#include <nel/misc/algo.h>
#include <nel/misc/bit_mem_stream.h>
#include <nel/misc/config_file.h>
#include <nel/misc/command.h>
#include <nel/misc/common.h>
#include <nel/misc/displayer.h>
#include <nel/misc/events.h>
#include <nel/misc/event_server.h>
#include <nel/misc/event_listener.h>
#include <nel/misc/fast_mem.h>
#include <nel/misc/file.h>
#include <nel/misc/hierarchical_timer.h>
#include <nel/misc/i_xml.h>
#include <nel/misc/matrix.h>
#include <nel/misc/mem_displayer.h>
#include <nel/misc/mem_stream.h>
#include <nel/misc/o_xml.h>
#include <nel/misc/path.h>
#include <nel/misc/progress_callback.h>
#include <nel/misc/plane.h>
#include <nel/misc/quat.h>
#include <nel/misc/reader_writer.h>
#include <nel/misc/report.h>
#include <nel/misc/rgba.h>
#include <nel/misc/sha1.h>
#include <nel/misc/sheet_id.h>
#include <nel/misc/smart_ptr.h>
#include <nel/misc/stream.h>
#include <nel/misc/stream_inline.h>
#include <nel/misc/string_common.h>
#include <nel/misc/string_mapper.h>
#include <nel/misc/system_info.h>
#include <nel/misc/thread.h>
#include <nel/misc/time_nl.h>
#include <nel/misc/value_smoother.h>
#include <nel/misc/vector.h>
#include <nel/misc/vectord.h>
#include <nel/misc/vector_2d.h>

#include <nel/3d/animation_time.h>
#include <nel/3d/frustum.h>
#include <nel/3d/viewport.h>

#include <nel/3d/u_animation.h>
#include <nel/3d/u_animation_set.h>
#include <nel/3d/u_camera.h>
#include <nel/3d/u_cloud_scape.h>
#include <nel/3d/u_driver.h>
#include <nel/3d/u_instance.h>
#include <nel/3d/u_instance_group.h>
#include <nel/3d/u_landscape.h>
#include <nel/3d/u_light.h>
#include <nel/3d/u_material.h>
#include <nel/3d/u_scene.h>
#include <nel/3d/u_shape.h>
#include <nel/3d/u_skeleton.h>
#include <nel/3d/u_texture.h>
#include <nel/3d/u_text_context.h>
#include <nel/3d/u_track.h>
#include <nel/3d/u_particle_system_instance.h>
#include <nel/3d/u_play_list.h>
#include <nel/3d/u_play_list_manager.h>
#include <nel/3d/u_point_light.h>
#include <nel/3d/u_visual_collision_entity.h>
#include <nel/3d/u_visual_collision_manager.h>

#include <3d/landscape.h>
#include <3d/material.h>
#include <3d/mesh_base.h>
#include <3d/mesh_base_instance.h>
#include <3d/mesh_blender.h>
#include <3d/mesh_block_manager.h>
#include <3d/mesh_geom.h>
#include <3d/mesh.h>
#include <3d/mesh_instance.h>
#include <3d/mesh_mrm.h>
#include <3d/mesh_mrm_instance.h>
#include <3d/mesh_mrm_skinned.h>
#include <3d/mesh_mrm_skinned_instance.h>
#include <3d/mesh_multi_lod.h>
#include <3d/mesh_multi_lod_instance.h>
#include <3d/mesh_morpher.h>
#include <3d/mesh_vertex_program.h>
#include <3d/meshvp_per_pixel_light.h>
#include <3d/meshvp_wind_tree.h>
#include <3d/mrm_builder.h>
#include <3d/mrm_internal.h>
#include <3d/mrm_level_detail.h>
#include <3d/mrm_mesh.h>
#include <3d/mrm_parameters.h>
#include <3d/patch.h>
#include <3d/quad_grid.h>
#include <3d/scene.h>
#include <3d/scene_user.h>
#include <3d/shape.h>
#include <3d/shape_bank.h>
#include <3d/skeleton_model.h>
#include <3d/skeleton_shape.h>
#include <3d/stripifier.h>
#include <3d/tangent_space_build.h>
#include <3d/texture_cube.h>
#include <3d/texture_file.h>
#include <3d/texture_file.h>
#include <3d/transform_shape.h>
#include <3d/vertex_buffer.h>
#include <3d/visual_collision_manager.h>
#include <3d/visual_collision_mesh.h>
#include <3d/water_model.h>
#include <3d/water_shape.h>
#include <3d/water_height_map.h>
#include <3d/water_pool_manager.h>

#include <nel/pacs/u_move_container.h>
#include <nel/pacs/u_move_primitive.h>
#include <nel/pacs/u_global_retriever.h>
#include <nel/pacs/u_global_position.h>

#include <nel/sound/u_audio_mixer.h>
#include <nel/sound/u_listener.h>
#include <nel/sound/u_source.h>

#include <nel/georges/u_form.h>
#include <nel/georges/u_form_loader.h>
#include <nel/georges/u_form_dfn.h>
#include <nel/georges/u_form_elm.h>
#include <nel/georges/u_type.h>

#include <georges/form.h>
#include <georges/form_dfn.h>
#include <georges/form_elm.h> 
#include <georges/form_loader.h>
#include <georges/type.h>

#include "ISingleton.h"

#endif // NL_OS_WINDOWS


